name: evorgaming
description: A new Flutter project.
publish_to: 'none'

version: 0.0.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animations: ^2.0.0
  auto_size_text: ^2.1.0
  badges: ^1.1.6
  bot_toast: ^4.0.0+1
  button_picker: ^0.1.6
  cached_network_image: ^2.5.0
  carousel_slider: ^3.0.0
  clipboard: ^0.1.2+8
  dio: ^3.0.10
  double_back_to_close: ^1.0.2+mit
  external_app_launcher: ^0.0.1
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_bloc: ^6.1.3
  flutter_form_builder: ^4.2.0
  flutter_spinkit: ^4.1.2+1
  flutter_widget_from_html: ^0.5.2+1
  form_builder_phone_field: ^0.1.0
  image_picker_for_web: ^0.1.0+2
  image_picker: ^0.6.7+21
  otp_screen: ^0.0.3
  percent_indicator: ^2.1.9+1
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/login.webp