name: evorgaming
description: A new Flutter project.
publish_to: 'none'

version: 0.0.7+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animations: ^2.0.1
  auto_size_text: ^2.1.0
  badges: ^2.0.1
  bot_toast: ^4.0.1
  button_picker: ^0.1.6
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  clipboard: ^0.1.3
  dio: ^4.0.0
  double_back_to_close: ^2.0.0
  external_app_launcher: ^2.0.0
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter_bloc: ^7.3.0
  flutter_form_builder: ^6.1.0+1
  flutter_spinkit: ^5.1.0
  flutter_widget_from_html: ^0.7.0
  form_builder_phone_field: ^0.3.0
  image_picker_for_web: ^2.1.3
  image_picker: ^0.8.4+2
  otp_screen: ^0.0.3
  percent_indicator: ^3.0.1
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies: 
  dapackages: ^1.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/login.webp