name: evorgaming
description: A new Flutter project.
publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animations: ^1.1.2
  auto_size_text: ^2.1.0
  bot_toast: ^3.0.5
  button_picker: ^0.1.6
  cached_network_image: ^2.5.0
  dio: ^3.0.10
  external_app_launcher: ^0.0.1
  flutter_bloc: ^6.1.1
  flutter_form_builder: ^4.2.0
  flutter_spinkit: ^4.1.2+1
  flutter_widget_from_html: ^0.5.2-rc.2021011801
  form_builder_phone_field: ^0.1.0
  # image_picker_for_web: ^0.1.0+2
  image_picker: ^0.6.7+21
  percent_indicator: ^2.1.9+1
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  
# dependency_overrides:
#   intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/login.webp