name: evorgaming
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animations: ^1.1.2
  auto_size_text: ^2.1.0
  bot_toast: ^3.0.5
  cached_network_image: ^2.4.1
  dio: ^3.0.10
  flutter_bloc: ^6.1.1
  flutter_form_builder: ^4.0.2
  flutter_spinkit: ^4.1.2+1
  flutter_widget_from_html: ^0.5.1+5
  image_picker: ^0.6.7+15
  intl: ^0.16.1
  percent_indicator: ^2.1.8
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/login.webp